config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
  end

  def create
    safe_params = params.require(:task).permit(:title, :details)
    task = Task.new(safe_params)
    task.save
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    safe_params = params.require(:task).permit(:title, :details, :completed)
    @task.update(safe_params)
    redirect_to task_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/b533bfa0fb.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><%= @task.title %></h1>
<%= form_for(@task) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.check_box :completed %>
      <%= f.label "Completed" %> <br>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %> <br>

<button class='btn btn-primary'><%= link_to'Home Page', tasks_path, :style =>'color: white;' %></button>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul style="list-style-type: none;">
  <%@tasks.each do |task| %>
  <li>
    <% if task.completed == true %>
      <i class="far fa-check-square"></i>
    <% else %>
      <i class="far fa-square"></i>
    <% end %>
    <%= link_to task.title, task_path(task.id)%>
    <%= link_to task_path(task.id), method: "delete", data: { confirm: "Are you sure?" } do %>
      <i class="far fa-trash-alt"></i>
    <% end %>
  </li>
  <%end %>
</ul>

<%= link_to "+ Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for(Task.new) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %> <br>

<%= link_to'Home Page', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<button class='btn btn-primary'><%= link_to'Home', tasks_path, :style =>'color: white;'%></button>

<button class='btn btn-primary'><%= link_to'Edit', edit_task_path,:style =>'color: white;' %></button>